### ISSUE TITLE
Summary At The End Of Termination Run

### ISSUE THREAD

**Issue by Skullman** [RedHatQE/dva#52]
It would by great to have list of instances that WERE NOT terminated during termination run - as a summary output at the end of run. User can then scroll up to check what happened. Something like:
```
dva -c ~/.ssh/dva.yaml terminate -i /tmp/to_terminate.yaml
 i-03f770ae in a region eu-west-1 will be terminated.
The instance i-03f770ae in eu-west-1 region may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.
i-b04db61d in a region eu-west-1 will be terminated.
i-b04db61d eu-west-1 was terminated
i-7b4cb7d6 in a region eu-west-1 will be terminated.
i-7b4cb7d6 eu-west-1 was terminated

Summary of instances that WERE NOT terminated:
i-03f770ae
```

Or in case everything was fine:
```
dva -c ~/.ssh/dva.yaml terminate -i /tmp/to_terminate.yaml

i-b04db61d in a region eu-west-1 will be terminated.
i-b04db61d eu-west-1 was terminated
i-7b4cb7d6 in a region eu-west-1 will be terminated.
i-7b4cb7d6 eu-west-1 was terminated

All instances WERE terminated - congratulations, Scrooge.
```

**Comment by alexxa** [comment]
Fixed by commit fb439b1

2 scenarios: 
1) All founded instances were successfully terminated

` >> dva -c ~/.ssh/dva.yaml terminate -i /tmp/result.yaml -o /tmp/term.yaml`
`========================================================================`
`Requested instances to terminate:     20`
`========================================================================`
`Ami i-78394cb9 in    eu-central-1 region was terminated.`
`Ami i-eceae830 in  ap-southeast-2 region was terminated.`
`Ami i-379f97f5 in       us-west-1 region was terminated.`
`Ami i-7f339db6 in       us-west-2 region was terminated.`
`Ami i-4e794c8f in    eu-central-1 region was NOT FOUND.`
`Ami i-4e394c8f in    eu-central-1 region was terminated.`
`Ami i-3d37b2cf in  ap-northeast-1 region was terminated.`
`Ami i-76182295 in       sa-east-1 region was terminated.`
`Ami i-c6192325 in       sa-east-1 region was terminated.`
`Ami i-7dbb6baf in       us-east-1 region was terminated.`
`Ami i-71e425dc in       eu-west-1 region was terminated.`
`Ami i-8c6a6440 in  ap-southeast-1 region was terminated.`
`Ami i-e9ebe935 in  ap-southeast-2 region was terminated.`
`Ami i-21e4258c in       eu-west-1 region was terminated.`
`Ami i-369f97f4 in       us-west-1 region was terminated.`
`Ami i-7abb6ba8 in       us-east-1 region was terminated.`
`Ami i-97329c5e in       us-west-2 region was terminated.`
`Ami i-8d6a6441 in  ap-southeast-1 region was terminated.`
`Ami i-4e594c8f in    eu-central-1 region was NOT FOUND.`
`Ami i-f231b400 in  ap-northeast-1 region was terminated.`

`Termination Summary`
`========================================================================`
`Requested instances to terminate:    20`
`Terminated:                          18`
`Not found:                            2`
`Not terminated:                       0`

`All found instances were terminated.`

2) Some instanced could not be terminated
`>> dva -c ~/.ssh/dva.yaml terminate -i /tmp/result.yaml -o /tmp/term.yaml`
`========================================================================`
`Requested instances to terminate:     21`
`========================================================================`
`Ami i-4a24518b in    eu-central-1 region was terminated.`
`Ami i-59f2f085 in  ap-southeast-2 region was terminated.`
`Ami i-4418bdb6 in  ap-northeast-1 region was NOT FOUND.`
`Ami i-d8f2f004 in  ap-southeast-2 region was terminated.`
`Ami i-e667692a in  ap-southeast-1 region was terminated.`
`Ami i-85a9a147 in       us-west-1 region was terminated.`
`Ami i-4438bdb6 in  ap-northeast-1 region was terminated.`
`Ami i-4447bdb6 in  ap-northeast-1 region was NOT FOUND.`
`Ami i-81ca1a53 in       us-east-1 region was terminated.`
`Ami i-726668be in  ap-southeast-1 region was terminated.`
`The instance i-411228a2 in sa-east-1 region may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.`
`Ami i-4439bdb6 in  ap-northeast-1 region was NOT FOUND.`
`Ami i-7d13299e in       sa-east-1 region was terminated.`
`Ami i-81245140 in    eu-central-1 region was terminated.`
`Ami i-4438bdb4 in  ap-northeast-1 region was NOT FOUND.`
`Ami i-8239bc70 in  ap-northeast-1 region was terminated.`
`Ami i-b9a9a17b in       us-west-1 region was terminated.`
`Ami i-d209a71b in       us-west-2 region was terminated.`
`Ami i-f35ad95e in       eu-west-1 region was terminated.`
`Ami i-d309a71a in       us-west-2 region was terminated.`
`Ami i-4bcb1b99 in       us-east-1 region was terminated.`

`Termination Summary`
`========================================================================`
`Requested instances to terminate:    21`
`Terminated:                          16`
`Not found:                            4`
`Not terminated:                       1`
`Ami i-411228a2 in    sa-east-1 region was NOT TERMINATED.`

In origin, it's tabulated properly =)
